#!/bin/bash -ex

DOCKER_ARCH=${BUILD_ARCH:-amd64}
DOCKER_ORG=lopsided
DOCKER_IMAGE=archlinux-${DOCKER_ARCH}

docker build --build-arg ARCH=${DOCKER_ARCH} \
  -t $DOCKER_ORG/$DOCKER_IMAGE \
	-f Dockerfile .

docker build --build-arg ARCH=${DOCKER_ARCH} \
  -t $DOCKER_ORG/$DOCKER_IMAGE:devel \
	-f Dockerfile.devel .
