ARG ARCH
FROM lopsided/archlinux-$ARCH

RUN env


COPY $ARCHDIR /

RUN pacman -Syu --noconfirm --needed base-devel

# Remove current pacman database, likely outdated very soon
RUN rm /var/lib/pacman/sync/*
